In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
data=pd.read_csv("C:/Users/bedir/Downloads/odev_tenis.csv")
data

outlook  temperature  humidity  windy play
0      sunny           85        85  False   no
1      sunny           80        90   True   no
2   overcast           83        86  False  yes
3      rainy           70        96  False  yes
4      rainy           68        80  False  yes
5      rainy           65        70   True   no
6   overcast           64        65   True  yes
7      sunny           72        95  False   no
8      sunny           69        70  False  yes
9      rainy           75        80  False  yes
10     sunny           75        70   True  yes
11  overcast           72        90   True  yes
12  overcast           81        75  False  yes
13     rainy           71        91   True   no

In [4]:
outlook=data.iloc[:,0:1].values
le=preprocessing.LabelEncoder()
outlook[:,0]=le.fit_transform(data.iloc[:,0])
ohe=preprocessing.OneHotEncoder()
outlook=ohe.fit_transform(outlook).toarray()
outlook

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [5]:
p=data.iloc[:,-1:].values
p[:,-1]=le.fit_transform(data.iloc[:,-1])
p=ohe.fit_transform(p).toarray()
p

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [18]:
w=data.iloc[:,3].values.reshape(-1,1)
w=ohe.fit_transform(w).toarray()
w

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [19]:
numeric=data[["temperature","humidity"]]
numeric

temperature  humidity
0            85        85
1            80        90
2            83        86
3            70        96
4            68        80
5            65        70
6            64        65
7            72        95
8            69        70
9            75        80
10           75        70
11           72        90
12           81        75
13           71        91

In [23]:
sonuc=pd.DataFrame(data=outlook[:, :2],index=range(14),columns=["overcast","rainy"])
sonuc2=pd.DataFrame(data=w[:,:1],index=range(14),columns=["windy"])
sonuc3=pd.DataFrame(data=p[:,:1],index=range(14),columns=["play"])



In [25]:
s=pd.concat([sonuc,numeric,sonuc2],axis=1)
s


overcast  rainy  temperature  humidity  windy
0        0.0    0.0           85        85    1.0
1        0.0    0.0           80        90    0.0
2        1.0    0.0           83        86    1.0
3        0.0    1.0           70        96    1.0
4        0.0    1.0           68        80    1.0
5        0.0    1.0           65        70    0.0
6        1.0    0.0           64        65    0.0
7        0.0    0.0           72        95    1.0
8        0.0    0.0           69        70    1.0
9        0.0    1.0           75        80    1.0
10       0.0    0.0           75        70    0.0
11       1.0    0.0           72        90    0.0
12       1.0    0.0           81        75    1.0
13       0.0    1.0           71        91    0.0

In [30]:
veri=pd.concat([s,sonuc3],axis=1)
veri

overcast  rainy  temperature  humidity  windy  play
0        0.0    0.0           85        85    1.0   1.0
1        0.0    0.0           80        90    0.0   1.0
2        1.0    0.0           83        86    1.0   0.0
3        0.0    1.0           70        96    1.0   0.0
4        0.0    1.0           68        80    1.0   0.0
5        0.0    1.0           65        70    0.0   1.0
6        1.0    0.0           64        65    0.0   0.0
7        0.0    0.0           72        95    1.0   1.0
8        0.0    0.0           69        70    1.0   0.0
9        0.0    1.0           75        80    1.0   0.0
10       0.0    0.0           75        70    0.0   0.0
11       1.0    0.0           72        90    0.0   0.0
12       1.0    0.0           81        75    1.0   0.0
13       0.0    1.0           71        91    0.0   1.0

In [27]:
x_train,x_test,y_train,y_test=train_test_split(s,sonuc3,test_size=0.3,random_state=0)

In [28]:
regressor=LinearRegression()
regressor.fit(x_train,y_train)

y_pred=regressor.predict(x_test)
y_pred

array([[0.25766369],
       [0.24628012],
       [0.21001443],
       [0.72818771],
       [0.21427549]])

In [36]:
values=veri.iloc[:,:-1]
values

overcast  rainy  temperature  humidity  windy
0        0.0    0.0           85        85    1.0
1        0.0    0.0           80        90    0.0
2        1.0    0.0           83        86    1.0
3        0.0    1.0           70        96    1.0
4        0.0    1.0           68        80    1.0
5        0.0    1.0           65        70    0.0
6        1.0    0.0           64        65    0.0
7        0.0    0.0           72        95    1.0
8        0.0    0.0           69        70    1.0
9        0.0    1.0           75        80    1.0
10       0.0    0.0           75        70    0.0
11       1.0    0.0           72        90    0.0
12       1.0    0.0           81        75    1.0
13       0.0    1.0           71        91    0.0

In [39]:
#geri eleme
import statsmodels.api as sm
X=np.append(arr=np.ones((14,1)).astype(int),values=veri.iloc[:,:-1],axis=1)
xl =veri.iloc[:, [0, 1, 2, 3,4]].values
xl=np.array(xl,dtype=float)
model=sm.OLS(sonuc3,xl).fit()
y=model.summary()
y

C:\Users\bedir\anaconda3\lib\site-packages\scipy\stats\_stats_py.py:1736: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                   play   R-squared (uncentered):                   0.641
Model:                            OLS   Adj. R-squared (uncentered):              0.442
Method:                 Least Squares   F-statistic:                              3.220
Date:                Wed, 07 Jun 2023   Prob (F-statistic):                      0.0610
Time:                        20:52:56   Log-Likelihood:                         -5.4776
No. Observations:                  14   AIC:                                      20.96
Df Residuals:                       9   BIC:                                      24.15
Df Model:                           5                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -0.6201      0.298     -2.078      0.067      -1.295       0.055
x2            -0.2464      0.293     -0.841      0.422      -0.909       0.416
x3            -0.0018      0.014     -0.124      0.904      -0.035       0.031
x4             0.0117      0.013      0.896      0.394      -0.018       0.041
x5            -0.3467      0.250     -1.386      0.199      -0.913       0.219
==============================================================================
Omnibus:                        0.759   Durbin-Watson:                   1.520
Prob(Omnibus):                  0.684   Jarque-Bera (JB):                0.639
Skew:                          -0.123   Prob(JB):                        0.726
Kurtosis:                       1.983   Cond. No.                         322.
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [46]:
sol=veri.iloc[:,:2]
sag=veri.iloc[:,3:5]

s=pd.concat([sol,sag],axis=1)
s

overcast  rainy  humidity  windy
0        0.0    0.0        85    1.0
1        0.0    0.0        90    0.0
2        1.0    0.0        86    1.0
3        0.0    1.0        96    1.0
4        0.0    1.0        80    1.0
5        0.0    1.0        70    0.0
6        1.0    0.0        65    0.0
7        0.0    0.0        95    1.0
8        0.0    0.0        70    1.0
9        0.0    1.0        80    1.0
10       0.0    0.0        70    0.0
11       1.0    0.0        90    0.0
12       1.0    0.0        75    1.0
13       0.0    1.0        91    0.0

In [47]:
veri=pd.concat([s,sonuc3],axis=1)
veri

overcast  rainy  humidity  windy  play
0        0.0    0.0        85    1.0   1.0
1        0.0    0.0        90    0.0   1.0
2        1.0    0.0        86    1.0   0.0
3        0.0    1.0        96    1.0   0.0
4        0.0    1.0        80    1.0   0.0
5        0.0    1.0        70    0.0   1.0
6        1.0    0.0        65    0.0   0.0
7        0.0    0.0        95    1.0   1.0
8        0.0    0.0        70    1.0   0.0
9        0.0    1.0        80    1.0   0.0
10       0.0    0.0        70    0.0   0.0
11       1.0    0.0        90    0.0   0.0
12       1.0    0.0        75    1.0   0.0
13       0.0    1.0        91    0.0   1.0

In [48]:
x_train,x_test,y_train,y_test=train_test_split(s,sonuc3,test_size=0.3,random_state=0)

In [49]:
regressor=LinearRegression()
regressor.fit(x_train,y_train)

y_pred=regressor.predict(x_test)
y_pred

array([[0.2425722 ],
       [0.22532724],
       [0.20475795],
       [0.71878246],
       [0.2171203 ]])